"""Eagerly import ORM model modules so mapper configuration sees the full graph."""

# Install the global before_insert listener that auto-populates ``public_ref``
# on every PublicRefMixin row. Done here so any code path that imports the
# models package wires the listener exactly once. Idempotent.
from app.services.public_refs import (
    install_public_ref_listener as _install_public_ref_listener,
)

from . import (
    accepted_science_repair,
    api_key,
    app_user,
    artifact_storage_capacity,
    author,
    calculation,
    dataset_release,
    energy_correction,
    execution_environment,
    geometry,
    group_additivity,
    idempotency,
    kinetics,
    level_of_theory,
    literature,
    literature_author,
    machine_review_curator_task,
    molecular_property_observation,
    network,
    network_pdep,
    reaction,
    reaction_atom_map,
    record_machine_review,
    record_review,
    reproducibility_assessment,
    scientific_record_supersession,
    software,
    species,
    statmech,
    submission,
    thermo,
    transition_state,
    transport,
    upload_job,
    user_session,
    workflow,
)

_install_public_ref_listener()


__all__ = [
    "accepted_science_repair",
    "api_key",
    "app_user",
    "artifact_storage_capacity",
    "author",
    "calculation",
    "dataset_release",
    "energy_correction",
    "execution_environment",
    "geometry",
    "group_additivity",
    "idempotency",
    "kinetics",
    "level_of_theory",
    "literature",
    "literature_author",
    "machine_review_curator_task",
    "molecular_property_observation",
    "network",
    "network_pdep",
    "reaction",
    "reaction_atom_map",
    "record_machine_review",
    "record_review",
    "reproducibility_assessment",
    "scientific_record_supersession",
    "software",
    "species",
    "statmech",
    "submission",
    "thermo",
    "transition_state",
    "transport",
    "upload_job",
    "user_session",
    "workflow",
]
