# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python
python:
  - "3.7"

stages:
  - test

before_install:
  # Setup python environment
  - source devtools/travis_ci_before_install.sh
  - python -V
  # Set git info
  - git config --global user.name "Travis Deploy"
  - git config --global user.email "alongd@mit.edu"

cache: pip

jobs:
  include:
    - stage: test
      install:
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - conda env create -f environment.yml
        - source activate tck_env
        - conda install -y -c conda-forge codecov
        - conda list
      script:
        - coverage run -m pytest -ra
        - coverage report
        - codecov
