codecov:
  token: 62d527a2-32da-49f4-ac7a-8c5d7b193e57
  bot: codecov-io
  ci:
    - travis.org
  require_ci_to_pass: yes
coverage:
  range: 0..100
  round: nearest
  precision: 2
  ignore:
    - test_*.py
    - tckdb/_version.py
comment:
  layout: reach, diff, flags, files
  behavior: default
  require_changes: false # if true: only post the comment if coverage changes
  branches: # branch names that can post comment
    - master
