codecov:
  token: 62d527a2-32da-49f4-ac7a-8c5d7b193e57
  bot: "codecov-io"
  ci:
    - "travis.org"
  require_ci_to_pass: yes
coverage:
  range: 0..100
  round: nearest
  percision: 2
  ignore:
    - test_*.py
    - tckdb/_version.py
comment:
  layout: "reach, diff, flags, files"
  require_changes: false
  branches: master
