
services:
  db:
    image: postgres:13
    platform: linux/amd64  # Forces the use of amd64 architecture
    container_name: tckdb_postgres
    restart: always
    env_file:
      - ./tckdb/backend/app/core/.env
    ports:
      - "5433:5432"  # Maps host port 5433 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tckdb_network
    # # Uncomment healthcheck if needed
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  test-db:
    image: postgres:13
    platform: linux/amd64  # Ensures compatibility on AMD64 platforms
    container_name: tckdb_test_postgres
    restart: always
    env_file:
      - ./tckdb/backend/app/core/.env.test  # Separate env file for testing
    ports:
      - "5434:5432"  # Maps host port 5434 to container port 5432
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - tckdb_network
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "test_user"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  app:
    build: .
    platform: linux/amd64  # Forces the use of amd64 architecture
    container_name: tckdb_app
    env_file:
      - ./tckdb/backend/app/core/.env
    volumes:
      - ./tckdb:/code/tckdb
    # depends_on:
      # db:
      #   condition: service_healthy
      # test-db:
      #   condition: service_healthy
    networks:
      - tckdb_network

  pgadmin:
    image: dpage/pgadmin4
    platform: linux/amd64  # Ensures compatibility on AMD64 platforms
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: calvinpieters@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db
      - test-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - tckdb_network

volumes:
  postgres_data:
  postgres_test_data:
  pgadmin_data:

networks:
  tckdb_network:
    driver: bridge
