name: tck_env
channels:
  - defaults
  - rmg
  - conda-forge
  - anaconda
  - chembl
dependencies:
  - chembl_webresource_client
  - coverage
  - fastapi >=0.65.2
  - ipython
  - jupyter
  - msgpack-python
  - numpy
  - pint
  - psycopg2
  - pydantic
  - pytest
  - python >= 3.7
  - qcelemental
  - rmg::rdkit >= 2019.09.2.0
  - sqlalchemy
  - starlette
  - sphinx
  - sphinx_rtd_theme
  - uvicorn

  - cairo
  - cairocffi
  - rmg::cantera >=2.3.0
  - cclib
  - rmg::chemprop
  - coolprop
  - cython >=0.25.2
  - ffmpeg
  - rmg::gprof2dot
  - graphviz
  - h5py
  - jinja2
  - rmg::lpsolve55
  - markupsafe
  - matplotlib >=1.5
  - rmg::mopac
  - mpmath
  - muq2
  - networkx
  - nose
  - rmg::numdifftools
  - openbabel
  - pandas
  - psutil
  - rmg::pydas >=1.0.2
  - pydot
  - rmg::pydqed >=1.0.1
  - pymongo
  - pyparsing
  - pyrdl
  - python >=3.7
  - pyyaml
  - rmg::quantities
  - scikit-learn
  - scipy
  - rmg::symmetry
  - xlrd
  - xlwt
