name: tck_env
channels:
  - defaults
  - conda-forge
  - anaconda
  - chembl
dependencies:
  - alembic
  - chembl_webresource_client
  - coverage
  - fastapi
  - msgpack-python
  - numpy
  - pint
  - psycopg2
  - pydantic
  - pytest
  - qcelemental
  - rdkit
  - sqlalchemy
  - uvicorn
  - requests-cache
  - ffmpeg
  - h5py
  - httpx
  - jinja2
  - markupsafe
  - matplotlib >=1.5
  - mpmath
  - pandas
  - python-dotenv
  - pyparsing
  - pip
  - pip:
      - isbnlib
  - pyyaml
