name: tck_env
channels:
  - defaults
  - conda-forge
  - anaconda
  - chembl
dependencies:
  - alembic
  - chembl_webresource_client
  - coverage
  - fastapi
  - msgpack-python
  - numpy
  - pint
  - psycopg2
  - pydantic
  - pytest
  - qcelemental
  - rdkit
  - sqlalchemy
  - starlette
  - sphinx
  - sphinx_rtd_theme
  - uvicorn
  - requests-cache
  - cairo
  - cairocffi
  - cantera::cantera
  - ffmpeg
  - conda-forge::gprof2dot
  - graphviz
  - h5py
  - httpx
  - jinja2
  - markupsafe
  - matplotlib >=1.5
  - mpmath
  - pandas
  - psutil
  - pydot
  - python-dotenv
  - pyparsing
  - pip
  - pip:
      - isbnlib
  - pyyaml
  - quantities
  - xlrd
  - xlwt
