name: tck_env
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - coverage
  - fastapi=0.46.0
  - ipython
  - jupyter
  - numpy
  - psycopg2
  - pydantic
  - pytest
  - python >=3.7
  - qcelemental
  - sqlalchemy
  - starlette
  - uvicorn
