name: tck_env
channels:
  - defaults
  - rmg
  - rdkit
  - cantera
  - pytorch
  - conda-forge
  - anaconda
  - chembl
dependencies:
  - chembl_webresource_client
  - coverage
  - fastapi = 0.46.0
  - ipython
  - jupyter
  - msgpack-python
  - numpy
  - pint
  - psycopg2
  - pydantic
  - pytest
  - python >= 3.7
  - qcelemental
  - rdkit >= 2019.09.1.0
  - sqlalchemy
  - starlette
  - sphinx
  - sphinx_rtd_theme
  - uvicorn

  - cairo
  - cairocffi
  - cantera >=2.3.0
  - cclib
  - chemprop
  - coolprop
  - cython >=0.25.2
  - ffmpeg
  - gprof2dot
  - graphviz
  - h5py
  - jinja2
  - lpsolve55
  - markupsafe
  - matplotlib >=1.5
  - mopac
  - mpmath
  - muq2
  - networkx
  - nose
  - numdifftools
  - openbabel
  - pandas
  - psutil
  - pydas >=1.0.1
  - pydot
  - pydqed >=1.0.0
  - pymongo
  - pyparsing
  - pyrdl
  - python >=3.7
  - pyyaml
  - quantities
  - scikit-learn
  - scipy
  - symmetry
  - xlrd
  - xlwt