name: tck_env
channels:
  - defaults
  - rmg
  - rdkit
  - cantera
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - coverage
  - fastapi = 0.46.0
  - ipython
  - jupyter
  - msgpack-python
  - numpy
  - pint
  - psycopg2
  - pydantic
  - pytest
  - python >= 3.7
  - qcelemental
  - rdkit >= 2019.09.1.0
  - rmg >= 3.0.0
  - sqlalchemy
  - starlette
  - sphinx
  - sphinx_rtd_theme
  - uvicorn
