#!/usr/bin/env bash
# Bootstrap a dev admin, log in, and mint an API key — single command.
#
# Idempotent: re-running with the same username promotes/refreshes the
# admin row, opens a fresh session cookie, and mints a new API key.
#
# Defaults:
#   username  : admin
#   password  : 1234
#   email     : admin@local
#   base url  : http://127.0.0.1:8000/api/v1
#   cookies   : ./cookies.txt   (relative to backend/)
#   API key label : dev-key
#
# Override any of these via env vars: TCKDB_USERNAME, TCKDB_PASSWORD,
# TCKDB_EMAIL, TCKDB_BASE_URL, TCKDB_COOKIES, TCKDB_API_KEY_LABEL.
#
# Requires: jq, curl, conda env tckdb_env, the API server running, and
# the standard DB env vars (DB_USER, DB_PASSWORD, DB_NAME, DB_HOST,
# DB_PORT) exported.

set -euo pipefail

USERNAME="${TCKDB_USERNAME:-admin}"
PASSWORD="${TCKDB_PASSWORD:-1234}"
EMAIL="${TCKDB_EMAIL:-admin@local}"
BASE_URL="${TCKDB_BASE_URL:-http://127.0.0.1:8000/api/v1}"
COOKIES="${TCKDB_COOKIES:-cookies.txt}"
API_KEY_LABEL="${TCKDB_API_KEY_LABEL:-dev-key}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(dirname "$SCRIPT_DIR")"

cd "$BACKEND_DIR"

case "$COOKIES" in
    /*) COOKIE_PATH="$COOKIES" ;;
    *)  COOKIE_PATH="$BACKEND_DIR/$COOKIES" ;;
esac

AUTH_ENV="${TCKDB_AUTH_ENV:-$BACKEND_DIR/.tckdb_auth.env}"
API_KEY_FILE="${TCKDB_API_KEY_FILE:-$BACKEND_DIR/.tckdb_api_key}"

# Default DB env vars to the local docker-compose dev DB if unset, so the
# script works out of the box for a fresh clone.
export DB_USER="${DB_USER:-tckdb}"
export DB_PASSWORD="${DB_PASSWORD:-tckdb}"
export DB_NAME="${DB_NAME:-tckdb_dev}"
export DB_HOST="${DB_HOST:-127.0.0.1}"
export DB_PORT="${DB_PORT:-5432}"

echo "==> Bootstrapping admin user '$USERNAME' (db=$DB_NAME)"
PYTHONPATH="$BACKEND_DIR${PYTHONPATH:+:$PYTHONPATH}" \
    TCKDB_BOOTSTRAP_PASSWORD="$PASSWORD" \
    conda run -n tckdb_env --no-capture-output \
        python scripts/bootstrap_admin.py \
            --username "$USERNAME" \
            --email "$EMAIL"

echo "==> Logging in as '$USERNAME' (cookie jar=$COOKIE_PATH)"
rm -f "$COOKIE_PATH"
LOGIN_RESPONSE="$(curl -sS -X POST "$BASE_URL/auth/login" \
    -H 'Content-Type: application/json' \
    -c "$COOKIE_PATH" \
    --fail-with-body \
    -d "{\"username\":\"$USERNAME\",\"password\":\"$PASSWORD\"}")"
echo "    logged in as $(jq -r '.username + " (role=" + .role + ")"' <<<"$LOGIN_RESPONSE")"

echo "==> Minting API key (label=$API_KEY_LABEL)"
KEY_RESPONSE="$(curl -sS -X POST "$BASE_URL/auth/api-keys" \
    -H 'Content-Type: application/json' \
    -b "$COOKIE_PATH" \
    --fail-with-body \
    -d "{\"label\":\"$API_KEY_LABEL\"}")"

API_KEY="$(jq -r '.key' <<<"$KEY_RESPONSE")"

cat > "$AUTH_ENV" <<EOF
# Generated by scripts/dev_login.sh
# Local dev credentials only. Do not commit.
export TCKDB_API_KEY='$API_KEY'
export TCKDB_BASE_URL='$BASE_URL'
export TCKDB_COOKIES='$COOKIE_PATH'
EOF

printf '%s\n' "$API_KEY" > "$API_KEY_FILE"

chmod 600 "$AUTH_ENV" "$API_KEY_FILE"
chmod 600 "$COOKIE_PATH" 2>/dev/null || true

MASKED_API_KEY="${API_KEY:0:6}…${API_KEY: -4}"

cat <<EOF

==> Done.
    Cookie jar    : $COOKIE_PATH
    Auth env      : $AUTH_ENV
    API key file  : $API_KEY_FILE
    API key       : $MASKED_API_KEY

To use the key in this terminal:
    source "$AUTH_ENV"

To test:
    curl -H "X-API-Key: \$TCKDB_API_KEY" $BASE_URL/auth/me
EOF
