"""Guard: no schema identifier silently overflows PostgreSQL's 63-char limit.

PostgreSQL truncates any identifier (table / constraint / index / enum-type
name) longer than ``NAMEDATALEN - 1`` = 63 characters. SQLAlchemy hides this by
deterministically truncating over-long *generated* names (from
``NAMING_CONVENTION``) to a 63-char name with a short hash suffix before it
emits DDL. That means a name we *think* we declared can differ from the name
actually stored in the database, and the whole scheme only works because the
ORM and every migration truncate identically. It is fragile and opaque:

* an autogenerate diff can churn if the truncation ever shifts,
* ``ALTER … RENAME CONSTRAINT`` / ``DROP CONSTRAINT`` in a migration must
  spell the *truncated* name exactly.

Two migrations removed all reliance on that truncation by giving every
over-long foreign key an explicit short ``name=``:

* revision ``d9c4a1e7f2b6`` — ``transition_state_selection``'s FK
  (``fk_ts_selection_transition_state``);
* revision ``f4a7c2e9b1d3`` — the remaining 25 over-63 foreign keys.

With those in place there are **no** legitimately-truncated identifiers left,
so this guard now enforces a hard rule with **no exceptions**: every raw name
declared by the ORM metadata must already be <= 63 chars. A new over-long
identifier means the schema is silently depending on truncation again — fix it
by giving the object an explicit short ``name=`` rather than relaxing this test.

Scope: this guard checks identifiers reachable from ``Base.metadata`` — table,
constraint, index, and enum-type names. Identifiers created only in raw SQL
inside a migration (e.g. expression / GIST indexes emitted with
``op.execute``) are out of ORM-metadata scope and are not checked here; keep
those <= 63 chars by hand when writing the migration.
"""

from __future__ import annotations

from sqlalchemy import Enum as SAEnum

import app.db.models  # noqa: F401  (populates Base.metadata)
from app.db.base import Base

# PostgreSQL NAMEDATALEN - 1.
_MAX_IDENTIFIER_LENGTH = 63

# Convention-generated names that historically exceeded 63 chars on deployed
# databases and relied on SQLAlchemy's deterministic truncation.
#
# This set is now INTENTIONALLY EMPTY: every such foreign key was given an
# explicit short ``name=`` (migrations ``d9c4a1e7f2b6`` and ``f4a7c2e9b1d3``).
# Do NOT add entries to silence a failure — give the offending object an
# explicit short ``name=`` (<= 63 chars, unique within its table) instead, e.g.
# ``ForeignKey(..., name="fk_<short_table>_<columns>")``. Keeping this set empty
# is the whole point of the guard.
_KNOWN_TRUNCATED_IDENTIFIERS: frozenset[str] = frozenset()


def _iter_named_objects():
    """Yield ``(table_name, kind, raw_name)`` for every named table,
    constraint, index, and enum type reachable from ``Base.metadata``.

    ``raw_name`` is the name exactly as declared / generated by the naming
    convention — before any truncation SQLAlchemy would apply at DDL-compile
    time. We deliberately never call ``IdentifierPreparer.format_constraint`` /
    ``format_index`` here: for an *explicit* name longer than 63 chars those
    raise ``sqlalchemy.exc.IdentifierError`` during iteration, which would mask
    the curated assertion failure below. Checking the raw string length is both
    sufficient and lets the length test report the offender cleanly.
    """
    seen_enum_names: set[str] = set()
    for table in Base.metadata.tables.values():
        yield table.name, "table", table.name
        for constraint in table.constraints:
            if constraint.name is None:
                continue
            yield table.name, type(constraint).__name__, str(constraint.name)
        for index in table.indexes:
            if index.name is None:
                continue
            yield table.name, "Index", str(index.name)
        # Enum type names are real PostgreSQL identifiers (CREATE TYPE ... AS
        # ENUM). A shared enum can appear on many columns/tables; report each
        # distinct type name once, attributed to the first table it is seen on.
        for column in table.columns:
            col_type = column.type
            if isinstance(col_type, SAEnum) and col_type.name:
                name = str(col_type.name)
                if name in seen_enum_names:
                    continue
                seen_enum_names.add(name)
                yield table.name, "EnumType", name


def test_no_reliance_on_identifier_truncation() -> None:
    """Every raw ORM identifier must be <= 63 chars, with no exceptions.

    ``_KNOWN_TRUNCATED_IDENTIFIERS`` is intentionally empty; an over-long name
    means the schema is silently depending on truncation again. Fix it by
    giving the object an explicit short ``name=``.
    """
    offenders = [
        (table, kind, raw, len(raw))
        for table, kind, raw in _iter_named_objects()
        if len(raw) > _MAX_IDENTIFIER_LENGTH
        and raw not in _KNOWN_TRUNCATED_IDENTIFIERS
    ]
    assert not offenders, (
        "Schema identifier(s) exceed PostgreSQL's "
        f"{_MAX_IDENTIFIER_LENGTH}-char limit and would rely on silent "
        "SQLAlchemy truncation:\n"
        + "\n".join(f"  {t}.{k}: {n!r} ({ln} chars)" for t, k, n, ln in offenders)
        + "\n\nGive the object an explicit short name=, e.g. "
        'ForeignKey(..., name="fk_<short_table>_<columns>") (or SAEnum(..., '
        'name="<short_enum>")), keeping it '
        f"<= {_MAX_IDENTIFIER_LENGTH} chars and unique within its table. "
        "Do NOT append to _KNOWN_TRUNCATED_IDENTIFIERS to silence this."
    )


def test_known_truncated_allow_list_is_empty() -> None:
    """The legacy allow-list must stay empty.

    A non-empty allow-list would re-introduce reliance on silent truncation.
    Every historically-truncated FK now has an explicit short name.
    """
    assert _KNOWN_TRUNCATED_IDENTIFIERS == frozenset()


def test_transition_state_selection_fk_has_explicit_short_name() -> None:
    """Regression lock for the fix in migration ``d9c4a1e7f2b6``.

    The ``transition_state_selection.transition_state_id`` FK must keep its
    explicit short name and must not slip back into the truncated form.
    """
    table = Base.metadata.tables["transition_state_selection"]
    fk = next(
        c
        for c in table.foreign_key_constraints
        if next(iter(c.columns)).name == "transition_state_id"
    )
    assert fk.name == "fk_ts_selection_transition_state", fk.name
    assert len(str(fk.name)) <= _MAX_IDENTIFIER_LENGTH
    assert fk.name not in _KNOWN_TRUNCATED_IDENTIFIERS
