"""Generic synchronous Python HTTP client for the TCKDB API."""

from importlib.metadata import PackageNotFoundError, version

from tckdb_client.client import (
    ArtifactUploadBatchResult,
    TCKDBClient,
    TCKDBResponse,
    UPLOAD_ENDPOINTS,
)
from tckdb_client.errors import (
    TCKDBAuthenticationError,
    TCKDBConflictError,
    TCKDBConnectionError,
    TCKDBError,
    TCKDBForbiddenError,
    TCKDBHTTPError,
    TCKDBIdempotencyConflictError,
    TCKDBPaginationError,
    TCKDBValidationError,
)
from tckdb_client.idempotency import make_idempotency_key, validate_idempotency_key
from tckdb_client.replay import (
    ClientFactory,
    ReplayFailure,
    ReplaySummary,
    replay_bundle,
)
from tckdb_client.scientific_types import (
    ArtifactRecord,
    ArtifactSearchResponse,
    ErrorEnvelope,
    KineticsRecord,
    KineticsSearchResponse,
    NetworkKineticsRecord,
    NetworkKineticsSearchResponse,
    NetworkRecord,
    NetworkSearchResponse,
    Pagination,
    ReactionKineticsResponse,
    ReactionRecord,
    ReactionSearchResponse,
    ReviewStatusSummary,
    ScientificRequestEcho,
    ScientificSearchResponse,
    SpeciesCalculationRecord,
    SpeciesCalculationsSearchResponse,
    SpeciesRecord,
    SpeciesSearchResponse,
    SpeciesThermoResponse,
    StatmechRecord,
    StatmechSearchResponse,
    ThermoRecord,
    ThermoSearchResponse,
    TransportRecord,
    TransportSearchResponse,
)

__all__ = [
    "ArtifactUploadBatchResult",
    "TCKDBClient",
    "TCKDBResponse",
    "UPLOAD_ENDPOINTS",
    "TCKDBError",
    "TCKDBConnectionError",
    "TCKDBHTTPError",
    "TCKDBAuthenticationError",
    "TCKDBForbiddenError",
    "TCKDBValidationError",
    "TCKDBConflictError",
    "TCKDBIdempotencyConflictError",
    "TCKDBPaginationError",
    "validate_idempotency_key",
    "make_idempotency_key",
    "ClientFactory",
    "ReplayFailure",
    "ReplaySummary",
    "replay_bundle",
    "ArtifactRecord",
    "ArtifactSearchResponse",
    "ErrorEnvelope",
    "KineticsRecord",
    "KineticsSearchResponse",
    "NetworkKineticsRecord",
    "NetworkKineticsSearchResponse",
    "NetworkRecord",
    "NetworkSearchResponse",
    "Pagination",
    "ReactionKineticsResponse",
    "ReactionRecord",
    "ReactionSearchResponse",
    "ReviewStatusSummary",
    "ScientificRequestEcho",
    "ScientificSearchResponse",
    "SpeciesCalculationRecord",
    "SpeciesCalculationsSearchResponse",
    "SpeciesRecord",
    "SpeciesSearchResponse",
    "SpeciesThermoResponse",
    "StatmechRecord",
    "StatmechSearchResponse",
    "ThermoRecord",
    "ThermoSearchResponse",
    "TransportRecord",
    "TransportSearchResponse",
]

try:
    __version__ = version("tckdb-client")
except PackageNotFoundError:
    __version__ = "0.0.0+local"
