# Generic, formatter-friendly config.
select = ["B", "D3", "E", "F"]

ignore = [
    # Never enforce `E501` (line length violations). This should be handled by formatters.
    "E501", 

    # Ignore calling function in dependencies injection - used in fast-api routes 
    "B008"
]
