"""add calc_spin_diagnostic

Brand-new one-to-one satellite table for parsed spin-contamination
``<S^2>`` evidence, the companion to ``calc_wavefunction_diagnostic``.
No data has ever lived in it, so this is a plain create/drop revision
(see ``.claude/rules/migration-rules.md``). The two species expression
indexes that autogenerate reports as "removed" (``ix_species_formula_lookup``
and ``ix_species_entry_mol_gist``) are known migration-only artifacts and
are intentionally NOT touched here.

Revision ID: b38b43af6460
Revises: 4869f598737d
Create Date: 2026-07-13 17:57:38.942850

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b38b43af6460"
down_revision: Union[str, Sequence[str], None] = "4869f598737d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calc_spin_diagnostic",
        sa.Column("calculation_id", sa.BigInteger(), nullable=False),
        sa.Column("s_squared", sa.Float(), nullable=False),
        sa.Column("s_squared_expected", sa.Float(), nullable=True),
        sa.Column("s_squared_annihilated", sa.Float(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("s_squared >= 0", name=op.f("ck_calc_spin_diagnostic_s_squared_ge_0")),
        sa.CheckConstraint(
            "s_squared_annihilated IS NULL OR s_squared_annihilated >= 0",
            name=op.f("ck_calc_spin_diagnostic_s_squared_annihilated_ge_0"),
        ),
        sa.CheckConstraint(
            "s_squared_expected IS NULL OR s_squared_expected >= 0",
            name=op.f("ck_calc_spin_diagnostic_s_squared_expected_ge_0"),
        ),
        sa.ForeignKeyConstraint(
            ["calculation_id"],
            ["calculation.id"],
            name=op.f("fk_calc_spin_diagnostic_calculation_id_calculation"),
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
            name=op.f("fk_calc_spin_diagnostic_created_by_app_user"),
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("calculation_id", name=op.f("pk_calc_spin_diagnostic")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calc_spin_diagnostic")
    # ### end Alembic commands ###
