"""Constraint ESS change

Revision ID: 16864e48c02c
Revises: d14a721ff6c8
Create Date: 2024-10-18 18:23:36.435903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16864e48c02c'
down_revision: Union[str, None] = 'd14a721ff6c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ess_name_key', 'ess', type_='unique')
    op.create_unique_constraint('ess_name_version_revision_uc', 'ess', ['name', 'version', 'revision'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ess_name_version_revision_uc', 'ess', type_='unique')
    op.create_unique_constraint('ess_name_key', 'ess', ['name'])
    # ### end Alembic commands ###
