"""Establish Bot to Species and NonPhysicalSpecies relationships

Revision ID: 28b44a6ca6a3
Revises: 58455667652b
Create Date: 2024-10-10 12:54:53.404178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b44a6ca6a3'
down_revision: Union[str, None] = '58455667652b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
