"""Add new_field to NonPhysicalSpecies

Revision ID: 58455667652b
Revises: dc57fb31be79
Create Date: 2024-10-10 12:18:32.287514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58455667652b'
down_revision: Union[str, None] = 'dc57fb31be79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nonphysicalspecies', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('nonphysicalspecies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('nonphysicalspecies', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nonphysicalspecies', 'deleted_at')
    op.drop_column('nonphysicalspecies', 'updated_at')
    op.drop_column('nonphysicalspecies', 'created_at')
    # ### end Alembic commands ###
