"""Add orcid column to author table

Revision ID: 6374c96d76cf
Revises: bbdc2988a3a7
Create Date: 2024-10-18 17:51:56.550259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6374c96d76cf'
down_revision: Union[str, None] = 'bbdc2988a3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('orcid', sa.String(length=19), nullable=True))
    op.create_index(op.f('ix_author_orcid'), 'author', ['orcid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_orcid'), table_name='author')
    op.drop_column('author', 'orcid')
    # ### end Alembic commands ###
