"""The producer contract ships in the package and can be read from it.

The contract is generated by the backend (``backend/scripts/
generate_producer_contract.py``); its freshness is checked there, because
only the backend can import the routes it is rendered from. What this file
checks is the other half: that the files reach a *user* of the package.

An editable install reads the source tree, so ``importlib.resources``
finding the files proves nothing about the wheel -- a missing
``package-data`` glob would pass every other test here and ship an empty
``contract/`` directory. ``test_the_wheel_ships_the_contract`` builds the
wheel and looks inside it, which is the only check that can fail for that.
"""

from __future__ import annotations

import importlib.util
import json
import pathlib
import re
import shutil
import subprocess
import sys
import zipfile

import pytest
import tckdb_schemas
from tckdb_schemas import contract

PACKAGE_DIR = pathlib.Path(__file__).resolve().parents[1]
PYPROJECT = PACKAGE_DIR / "pyproject.toml"


def _pyproject_version() -> str:
    match = re.search(r'^version\s*=\s*"([^"]+)"', PYPROJECT.read_text(), flags=re.MULTILINE)
    assert match is not None
    return match.group(1)


def test_the_contract_is_found_through_the_package() -> None:
    path = contract.path()
    assert path.is_file(), path
    text = contract.markdown()
    assert text.startswith("# TCKDB producer contract")


def test_the_contract_names_the_version_it_ships_in() -> None:
    """Regenerated after the last bump, or the stamp would name another version."""
    assert f"**tckdb-schemas version `{_pyproject_version()}`**" in contract.markdown()


def test_every_shipped_schema_is_json_with_an_example() -> None:
    names = contract.schema_names()
    assert len(names) >= 16, names
    for name in names:
        schema = contract.json_schema(name)
        assert schema["title"] == name
        assert schema.get("examples"), f"{name} ships no example"
        assert f"schemas/{name}.schema.json" in contract.markdown(), f"{name} is not named in the contract"


def test_the_wire_models_accept_their_shipped_examples() -> None:
    """The schemas this package's own models produce validate their examples.

    The remaining surfaces' models live in the backend and are checked there
    against both the JSON Schema and the model.
    """
    from tckdb_schemas.workflows import (
        ComputedReactionUploadRequest,
        ComputedSpeciesUploadRequest,
        ConformerUploadRequest,
        TransitionStateUploadRequest,
    )

    for model in (
        ComputedReactionUploadRequest,
        ComputedSpeciesUploadRequest,
        ConformerUploadRequest,
        TransitionStateUploadRequest,
    ):
        schema = contract.json_schema(model.__name__)
        for example in schema["examples"]:
            model.model_validate(example)


def test_an_unknown_schema_name_is_refused() -> None:
    with pytest.raises(KeyError):
        contract.json_schema("NoSuchUploadRequest")


def test_changes_since_returns_only_newer_entries() -> None:
    text = (
        "# Changelog\n\n## 0.52.0 - 2026-09-29\n\nnew\n\n"
        "## 0.51.0 - 2026-09-27\n\nolder\n\n## 0.50.0 - 2026-09-27\n\noldest\n"
    )
    changes = contract.changes_since("0.50.0", text)
    assert "### 0.52.0" in changes and "### 0.51.0" in changes
    assert "new" in changes and "older" in changes
    assert "0.50.0" not in changes and "oldest" not in changes
    assert contract.changes_since("0.52.0", text) == ""


def test_changes_since_reads_the_shipped_changelog() -> None:
    changes = contract.changes_since("0.47.0")
    assert f"### {_pyproject_version()}" in changes
    assert "### 0.51.0" in changes
    assert "### 0.47.0" not in changes


def test_the_contract_prints_only_the_newest_entries_and_the_changelog_keeps_every_one() -> None:
    """The point of shipping the changelog: an entry the contract no longer prints is still reachable."""
    markdown = contract.markdown()
    section = markdown[markdown.index("\n## What changed\n") :]
    section = section[: section.index("\n## ", len("\n## What changed"))]
    printed = [line for line in section.splitlines() if line.startswith("### ")]
    assert 0 < len(printed) < 10
    assert printed[0].startswith(f"### {_pyproject_version()} ")
    assert "\n### 0.51.0 " not in section
    assert "### 0.51.0 " in contract.changes_since("0.50.0")
    assert contract.changelog_path().read_text(encoding="utf-8").startswith("# Changelog\n")


def _run(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "tckdb_schemas.contract", *args],
        capture_output=True,
        text=True,
        check=True,
    )


def test_the_command_prints_the_path_by_default() -> None:
    assert _run().stdout.strip() == str(contract.path())


def test_the_command_prints_the_contract() -> None:
    assert _run("--print").stdout == contract.markdown()


def test_the_command_prints_changes_since_a_version() -> None:
    out = _run("--since", "0.50.0").stdout
    assert "### 0.51.0" in out
    assert "### 0.50.0" not in out


def test_the_command_lists_the_schemas() -> None:
    lines = _run("--schemas").stdout.splitlines()
    assert len(lines) == len(contract.schema_names())
    assert any(line.startswith("ThermoUploadRequest\t") for line in lines)


def _setuptools_major() -> int | None:
    if importlib.util.find_spec("setuptools") is None:
        return None
    import setuptools

    return int(setuptools.__version__.split(".")[0])


def test_the_wheel_ships_the_contract(tmp_path: pathlib.Path) -> None:
    """Build the wheel and look inside it.

    Built from a copy of the project, not the checkout: setuptools builds in
    tree and reuses ``build/lib``, so a stale file left there by an earlier
    build could reach the wheel and make this test pass (or fail) on
    something the source no longer contains.
    """
    source = tmp_path / "src"
    shutil.copytree(
        PACKAGE_DIR,
        source,
        ignore=shutil.ignore_patterns("build", "*.egg-info", "__pycache__", ".pytest_cache"),
    )
    out = tmp_path / "dist"
    command = [sys.executable, "-m", "pip", "wheel", "--no-deps", "--quiet", "-w", str(out), str(source)]
    # ``license = "MIT"`` needs setuptools >= 77 (PEP 639). Reuse the
    # environment's setuptools when it is new enough; otherwise let pip build
    # in an isolated environment that fetches one.
    major = _setuptools_major()
    if major is not None and major >= 77:
        command.insert(4, "--no-build-isolation")
    subprocess.run(command, check=True, capture_output=True, text=True)
    wheels = list(out.glob("tckdb_schemas-*.whl"))
    assert len(wheels) == 1, wheels
    names = set(zipfile.ZipFile(wheels[0]).namelist())

    assert "tckdb_schemas/contract/__init__.py" in names
    assert "tckdb_schemas/contract/__main__.py" in names
    assert "tckdb_schemas/contract/PRODUCER_CONTRACT.md" in names
    assert "tckdb_schemas/contract/CHANGELOG.md" in names
    shipped_schemas = {name for name in names if name.startswith("tckdb_schemas/contract/schemas/")}
    expected = {f"tckdb_schemas/contract/schemas/{name}.schema.json" for name in contract.schema_names()}
    assert shipped_schemas == expected
    assert wheels[0].name.startswith(f"tckdb_schemas-{_pyproject_version()}-")
    with zipfile.ZipFile(wheels[0]) as wheel:
        shipped = json.loads(wheel.read("tckdb_schemas/contract/schemas/ThermoUploadRequest.schema.json"))
    assert shipped == contract.json_schema("ThermoUploadRequest")


def test_the_version_is_importable() -> None:
    assert tckdb_schemas.__version__


def test_printing_into_a_closed_pipe_is_quiet() -> None:
    """``--print | head`` must not end in a BrokenPipeError traceback."""
    process = subprocess.Popen(
        [sys.executable, "-m", "tckdb_schemas.contract", "--print"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    assert process.stdout is not None and process.stderr is not None
    process.stdout.readline()
    process.stdout.close()
    stderr = process.stderr.read().decode()
    process.wait(timeout=30)
    assert "Traceback" not in stderr, stderr
    assert "BrokenPipeError" not in stderr, stderr
