name: Deploy Documentation

on:
  push:
    branches:
      - master # Updated branch name
  pull_request:
    branches:
      - master # Updated branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CONDA_PKGS_DIRS: $HOME/conda_pkgs_dir

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Create Conda Package Directory
      - name: Create Conda Package Directory
        run: mkdir -p $HOME/conda_pkgs_dir

      # Step 3: Cache Conda Packages
      - name: Cache Conda Packages
        uses: actions/cache@v4
        with:
          path: $HOME/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('docs/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      # Step 4: Set up Miniconda
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: docs/environment.yml
          activate-environment: docs_env
          miniconda-version: latest
          conda-solver: libmamba

      # Step 5: Set PYTHONPATH
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=${{ github.workspace }}/tckdb:${{ github.workspace }}" >> $GITHUB_ENV

      # Step 6: Build Documentation
      - name: Build Documentation
        shell: bash -l {0}
        run: |
          conda activate docs_env
          cd docs
          make html

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' # Updated branch name
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/
